name: .NET Core
on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses:  cryptic-wizard/run-specflow-tests@v1.1.0-alpha2
      with:
        test-assembly-dll: RunSpecflowTests/bin/Debug/netcoreapp3.1/RunSpecflowTests.dll
        test-execution-json: RunSpecflowTests/bin/Debug/netcoreapp3.1/TestExecution.json
        output-html: CalculatorResults.html
        test-verbosity: minimal
        dotnet-version: netcoreapp3.1
        logger: trx
        logger-file-name: CalculatorResults.trx
    - name: Publish Specflow Test Results
      if: success() || failure()
      uses: actions/upload-artifact@v2
      with:
        name: SpecflowTestResults
        path: |
          CalculatorResults.html
          CalculatorResults.trx